"""
pack_for_ide.py - IDE build pipeline one-click packaging tool.

This script is ONLY used during IDE build (online environment with network).
It is NOT part of the runtime.

It downloads portable Python, fetches offline vendor wheels, copies skill code,
and generates a manifest.json for integrity verification.

Usage:
    python scripts/pack_for_ide.py \\
        --output ./build-output/evolving-agent \\
        --platform darwin-arm64 \\
        --include-vendor \\
        --include-portable-python \\
        [--skip-checksum]

Output directory structure:
    <output>/
    +-- runtime.json
    +-- manifest.json              <-- generated by this tool
    +-- evolving-agent/            <-- skill resources
    |   +-- SKILL.md
    |   +-- agents/
    |   +-- workflows/
    |   +-- references/
    |   +-- scripts/run.py
    +-- scripts/
    |   +-- bootstrap.py
    +-- requirements.txt
    +-- requirements-optional.txt
    +-- README.md
    +-- .runtime/
    |   +-- python/                <-- portable Python (extracted)
    +-- vendor/                    <-- offline wheels
        +-- PyYAML-*.whl
        +-- jieba-*.whl

Exit:
    stdout: JSON {"status":"ok","output":"...","platform":"...","manifest":"..."}
            or     {"status":"error","message":"..."}
    stderr: human-readable log messages
"""

import argparse
import datetime
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tarfile
import urllib.request
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RUNTIME_JSON = PROJECT_ROOT / "runtime.json"

VALID_PLATFORMS = [
    "linux-x86_64",
    "linux-aarch64",
    "darwin-x86_64",
    "darwin-arm64",
    "windows-x86_64",
]

PIP_PLATFORM_MAP = {
    "linux-x86_64": "manylinux2014_x86_64",
    "linux-aarch64": "manylinux2014_aarch64",
    "darwin-x86_64": "macosx_10_9_x86_64",
    "darwin-arm64": "macosx_11_0_arm64",
    "windows-x86_64": "win_amd64",
}

SKIP_PATTERNS = {
    "__pycache__",
    ".pytest_cache",
    ".git",
    ".github",
    ".opencode",
    "docs",
    "tests",
    "htmlcov",
    ".coverage",
}


def _ignore_patterns(directory, contents):
    ignored = []
    for name in contents:
        if name in SKIP_PATTERNS or name.endswith(".pyc"):
            ignored.append(name)
    return ignored


def _safe_extract_tar(tar: tarfile.TarFile, dest: Path) -> None:
    """Safely extract tar archive, rejecting path traversal."""
    dest_real = os.path.realpath(dest)
    for member in tar.getmembers():
        if os.path.isabs(member.name) or member.name.startswith(("..", "/")):
            raise RuntimeError(f"Unsafe tar path (absolute or parent ref): {member.name}")
        if member.issym() or member.islnk():
            link_target = os.path.realpath(os.path.join(dest_real, os.path.dirname(member.name), member.linkname))
            if not link_target.startswith(dest_real + os.sep) and link_target != dest_real:
                raise RuntimeError(f"Unsafe symlink in tar: {member.name} -> {member.linkname}")
        member_path = os.path.realpath(os.path.join(dest_real, member.name))
        if not member_path.startswith(dest_real + os.sep) and member_path != dest_real:
            raise RuntimeError(f"Path traversal attempt: {member.name}")
    if sys.version_info >= (3, 12):
        tar.extractall(dest, filter='data')
    else:
        tar.extractall(dest)


def _load_runtime_config():
    with open(RUNTIME_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


def _verify_symlinks_preserved(packed_dir: Path) -> None:
    py_bin = packed_dir / ".runtime" / "python" / "bin"
    if not py_bin.exists():
        return
    candidates = ["python3", "2to3", "pip3"]
    found_any_symlink = False
    for name in candidates:
        p = py_bin / name
        if p.exists():
            if p.is_symlink():
                found_any_symlink = True
            else:
                print(f"[pack] WARN: {name} is not a symlink (may be deref'd)", file=sys.stderr)
    if not found_any_symlink and any((py_bin / n).exists() for n in candidates):
        print("[pack] WARN: no symlinks found in portable Python bin/, may indicate deref bug", file=sys.stderr)


def copy_skill_code(output):
    print("[pack] Copying skill code...", file=sys.stderr)

    evolving_agent_src = PROJECT_ROOT / "evolving-agent"
    if evolving_agent_src.is_dir():
        shutil.copytree(
            evolving_agent_src,
            output / "evolving-agent",
            ignore=_ignore_patterns,
            symlinks=True,
        )

    scripts_dst = output / "scripts"
    scripts_dst.mkdir(parents=True, exist_ok=True)
    bootstrap_src = PROJECT_ROOT / "scripts" / "bootstrap.py"
    if bootstrap_src.is_file():
        shutil.copy2(bootstrap_src, scripts_dst / "bootstrap.py")

    for fname in ("runtime.json", "requirements.txt", "requirements-optional.txt", "README.md", "LICENSE"):
        src = PROJECT_ROOT / fname
        if src.is_file():
            shutil.copy2(src, output / fname)


def download_portable_python(output, platform, skip_checksum):
    print(f"[pack] Downloading portable Python for {platform}...", file=sys.stderr)

    cfg = _load_runtime_config()
    portable_cfg = cfg.get("python", {}).get("portable", {})
    url = portable_cfg.get("downloads", {}).get(platform)
    if not url:
        raise RuntimeError(f"No download URL for platform: {platform}")

    expected_checksum = portable_cfg.get("checksums", {}).get(platform, "")
    checksum_verified = False

    runtime_dir = output / ".runtime"
    runtime_dir.mkdir(parents=True, exist_ok=True)

    archive_path = runtime_dir / "python.tar.gz"

    print(f"[pack]   URL: {url}", file=sys.stderr)
    urllib.request.urlretrieve(url, str(archive_path))
    print(f"[pack]   Downloaded: {archive_path.stat().st_size} bytes", file=sys.stderr)

    if expected_checksum:
        if expected_checksum.startswith("sha256:"):
            expected_hex = expected_checksum[7:]
        else:
            expected_hex = expected_checksum
        print("[pack]   Verifying sha256 checksum...", file=sys.stderr)
        h = hashlib.sha256()
        with open(archive_path, "rb") as f:
            while True:
                chunk = f.read(8192)
                if not chunk:
                    break
                h.update(chunk)
        actual_hex = h.hexdigest()
        if actual_hex != expected_hex:
            archive_path.unlink(missing_ok=True)
            raise RuntimeError(
                f"Checksum mismatch for {platform}: "
                f"expected {expected_hex}, got {actual_hex}"
            )
        checksum_verified = True
        print("[pack]   Checksum OK", file=sys.stderr)
    else:
        if skip_checksum:
            print(
                "[pack]   WARNING: No checksum in runtime.json, skipping verification (--skip-checksum)",
                file=sys.stderr,
            )
        else:
            archive_path.unlink(missing_ok=True)
            raise RuntimeError(
                f"No checksum for {platform} in runtime.json. "
                "Use --skip-checksum to bypass."
            )

    print("[pack]   Extracting...", file=sys.stderr)
    with tarfile.open(archive_path) as tar:
        _safe_extract_tar(tar, runtime_dir)
    archive_path.unlink()

    python_bin = output / ".runtime" / "python" / "bin" / "python3"
    python_exe = output / ".runtime" / "python" / "python.exe"

    if not python_bin.is_file() and not python_exe.is_file():
        candidates = list(runtime_dir.rglob("python3")) + list(runtime_dir.rglob("python.exe"))
        if candidates:
            found = candidates[0]
            python_dir = found.parent
            while python_dir.name != "python" and python_dir != runtime_dir:
                python_dir = python_dir.parent
            if python_dir.name == "python":
                print(
                    f"[pack]   WARNING: Expected .runtime/python/ but found python at {python_dir}",
                    file=sys.stderr,
                )
            else:
                for item in runtime_dir.iterdir():
                    if item.is_dir() and item.name.startswith("cpython"):
                        target_dir = runtime_dir / "python"
                        if not target_dir.exists():
                            item.rename(target_dir)
                        break
        python_bin = output / ".runtime" / "python" / "bin" / "python3"
        python_exe = output / ".runtime" / "python" / "python.exe"

    if python_bin.is_file():
        print(f"[pack]   Python binary: {python_bin}", file=sys.stderr)
    elif python_exe.is_file():
        print(f"[pack]   Python binary: {python_exe}", file=sys.stderr)
    else:
        raise RuntimeError(
            f"Portable Python binary not found after extraction. "
            f"Expected {python_bin} or {python_exe}"
        )

    return checksum_verified


def download_vendor_wheels(output, platform):
    print(f"[pack] Downloading vendor wheels for {platform}...", file=sys.stderr)

    vendor_dir = output / "vendor"
    vendor_dir.mkdir(parents=True, exist_ok=True)

    requirements_file = output / "requirements.txt"
    if not requirements_file.is_file():
        print("[pack]   WARNING: requirements.txt not found, skipping vendor download", file=sys.stderr)
        return

    pip_plat = PIP_PLATFORM_MAP[platform]
    print(f"[pack]   pip platform: {pip_plat}", file=sys.stderr)

    cfg = _load_runtime_config()
    py_version = cfg.get("python", {}).get("recommended_version", "3.11")

    cmd = [
        sys.executable, "-m", "pip", "download",
        "--dest", str(vendor_dir),
        "--platform", pip_plat,
        "--only-binary=:all:",
        "--no-deps",
        "--python-version", py_version,
        "-r", str(requirements_file),
    ]

    print(f"[pack]   Running: {' '.join(cmd)}", file=sys.stderr)
    try:
        subprocess.check_call(cmd, stdout=sys.stderr, stderr=sys.stderr)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"pip download failed (exit {e.returncode})")


def _sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def _find_portable_python_version(output):
    python_bin = output / ".runtime" / "python" / "bin" / "python3"
    python_exe = output / ".runtime" / "python" / "python.exe"
    py_path = None
    if python_bin.is_file():
        py_path = str(python_bin)
    elif python_exe.is_file():
        py_path = str(python_exe)
    if py_path:
        try:
            ver_out = subprocess.check_output(
                [py_path, "-c", "import sys; print('.'.join(map(str, sys.version_info[:3])))"],
                stderr=subprocess.DEVNULL,
                timeout=5,
            ).decode().strip()
            return ver_out
        except Exception:
            pass
    return None


def generate_manifest(output, platform, checksum_verified=False, has_portable_python=True):
    print("[pack] Generating manifest.json...", file=sys.stderr)

    cfg = _load_runtime_config()
    files = []
    for root, dirs, names in os.walk(output):
        dirs[:] = [d for d in dirs if d not in ("__pycache__", ".pytest_cache")]
        for name in names:
            if name == "manifest.json":
                continue
            full_path = Path(root) / name
            rel_path = full_path.relative_to(output)
            sha256 = _sha256_file(full_path)
            size = full_path.stat().st_size
            files.append({
                "path": str(rel_path).replace(os.sep, "/"),
                "sha256": sha256,
                "size": size,
            })

    files.sort(key=lambda f: f["path"])

    vendor_dir = output / "vendor"
    vendor_wheels = []
    if vendor_dir.is_dir():
        for whl in sorted(vendor_dir.glob("*.whl")):
            vendor_wheels.append(whl.name)

    py_version = _find_portable_python_version(output) or cfg.get("python", {}).get("recommended_version", "3.11")

    portable_cfg = cfg.get("python", {}).get("portable", {})
    release_tag = portable_cfg.get("release_tag", "")

    manifest = {
        "skill_version": cfg.get("skill", {}).get("version", "unknown"),
        "cli_protocol": cfg.get("cli_protocol", {}).get("version", "v1"),
        "min_ide_version": cfg.get("cli_protocol", {}).get("min_ide_version", "0.5.0"),
        "platform": platform,
        "build_time": datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z"),
        "python_runtime": {
            "version": py_version,
            "source": portable_cfg.get("source", "python-build-standalone"),
            "release_tag": release_tag,
            "checksum_verified": checksum_verified,
        } if has_portable_python else None,
        "vendor_wheels": vendor_wheels,
        "files": files,
    }

    manifest_path = output / "manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    print(f"[pack]   manifest.json: {len(files)} files", file=sys.stderr)
    return manifest


def main():
    parser = argparse.ArgumentParser(
        description="Pack evolving-agent resources for IDE build pipeline (online, requires network)",
    )
    parser.add_argument(
        "--output", required=True,
        help="Output directory path",
    )
    parser.add_argument(
        "--platform", required=True,
        choices=VALID_PLATFORMS,
        help="Target platform",
    )
    parser.add_argument(
        "--include-vendor", action="store_true", default=True,
        help="Download vendor wheels (default: yes)",
    )
    parser.add_argument(
        "--no-vendor", action="store_false", dest="include_vendor",
        help="Skip vendor wheel download",
    )
    parser.add_argument(
        "--include-portable-python", action="store_true", default=True,
        help="Download portable Python (default: yes)",
    )
    parser.add_argument(
        "--no-portable-python", action="store_false", dest="include_portable_python",
        help="Skip portable Python download",
    )
    parser.add_argument(
        "--skip-checksum", action="store_true", default=False,
        help="Skip checksum verification when runtime.json checksums are empty",
    )

    args = parser.parse_args()
    output = Path(args.output).resolve()

    def _error(msg):
        json.dump({"status": "error", "message": msg}, sys.stdout)
        print()
        sys.exit(1)

    try:
        if output.exists():
            print(f"[pack] Removing existing output: {output}", file=sys.stderr)
            shutil.rmtree(output)
        output.mkdir(parents=True, exist_ok=True)

        copy_skill_code(output)

        checksum_verified = False
        if args.include_portable_python:
            checksum_verified = download_portable_python(output, args.platform, args.skip_checksum)

        if args.include_vendor:
            download_vendor_wheels(output, args.platform)

        manifest = generate_manifest(output, args.platform, checksum_verified=checksum_verified, has_portable_python=args.include_portable_python)

        _verify_symlinks_preserved(output)

        manifest_path = output / "manifest.json"
        result = {
            "status": "ok",
            "output": str(output),
            "platform": args.platform,
            "manifest": str(manifest_path),
        }
        json.dump(result, sys.stdout)
        print()
        print(f"[pack] Done: {output}", file=sys.stderr)

    except Exception as e:
        if output.exists():
            print(f"[pack] Cleaning up failed output: {output}", file=sys.stderr)
            try:
                shutil.rmtree(output)
            except Exception:
                pass
        _error(str(e))


if __name__ == "__main__":
    main()
